=== Politecnico-JIC2/Ejercicio5_MoverDatos/MoverDatos.dtd
<!ELEMENT ListaCompras (Venta+)>
        <!ELEMENT Venta (Ventaacredito|Ventainmediata)>
        <!ELEMENT Ventaacredito (Fechafinpago?,Cantidad)>
        <!ELEMENT Ventainmediata (Cantidad,Divisa)>
        <!ELEMENT Fechafinpago (#PCDATA) >
        <!ELEMENT Cantidad (#PCDATA)>
        <!ELEMENT Divisa (#PCDATA)>

=== Politecnico-JIC2/Ejercicio5_MoverDatos/MoverDatos.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE ListaCompras SYSTEM "MoverDatos.dtd">
<ListaCompras xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="MoverDatos.xsd">
    <Venta>
        <Ventaacredito>
            <Fechafinpago>2022-09-02</Fechafinpago>
            <Cantidad>8000</Cantidad>
        </Ventaacredito>
    </Venta>
    <Venta>
        <Ventaacredito>
            <Cantidad>36000</Cantidad>
        </Ventaacredito>
    </Venta>
    <Venta>
        <Ventainmediata>
            <Cantidad>600</Cantidad>
            <Divisa>DÃ³lares</Divisa>
        </Ventainmediata>
    </Venta>
</ListaCompras>
